spring.application.name=Spring_Boot_Application

server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/travel360_v2
spring.datasource.username=root
spring.datasource.password=Swathi@062004

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.open-in-view=false
